version: "1"

services:
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - test-network
    depends_on:
      - database

  backend:
    container_name: backend-container
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test-network
    depends_on:
      - database

  database:
    container_name: database-container
    build:
      context: ./database-app
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raj
    networks:
      - test-network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U yourUsername"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  test-network:
    driver: bridge
